# Generated by Django 4.2.2 on 2023-06-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jacket',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
