# Generated by Django 4.2.2 on 2023-07-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jackets', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Occasion',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='jacket',
        ),
        migrations.RemoveField(
            model_name='jacket',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='jacket',
            name='seasons',
        ),
        migrations.RemoveField(
            model_name='jacket',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
